version: "3.8"

services:
  server:
    image: 'nginx:stable-alpain'
    ports:
      - '8000:80'
    volumnes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro 
  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated # 로컬에 있는 src를 html경로에 바인드마운트함
    #ports:
    #  - '3000:9000' # 호스트 머신의 포트 : 컨테이너 내부 포트, 여기선 ㅇ나해도됨
  mysql:
    image: mysql:5.7
    env_file:
      - .env/mysql.env
    #environment: # 환경변수 따로 설정하는 법
    #  MYSQL_ROOT_PASSWORD
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html # src파일을 html경로에 바인드 마운트함
  #artisan:
  #npm:
