version: "3.8"

services:
  mysql:
    build:
    context: ./dockerFiles
    dockerfile: mysql.dockerfile
    volumes:
      - ./mysql/mysql-volume:var/lib/mysql
    ports:
      - '3306/3306'
  nginx:
    build:
    context: ./dockerFiles
    dockerfile: nginx.dockerfile
    depends_on:
      - mysql

  node:
    build:
    context: ./dockerFiles
    dockerfile: node.dockerfile
    depends_on:
      - mysql